---
metadata:
  title: My Video Podcast
  description: |
    A podcast about various topics. This block can be formatted using Markdown, with things like lists:

      * List item 1
      * List item 2
  language: en-us
  link: http://example.com/podcast
  itunes_image: http://example.com/images/podcast-cover.jpg
  itunes_category: Technology
  itunes_explicit: false
  itunes_author: Author Name
  itunes_email: contact@example.com
  rss_feed_url: https://example.com/podcast_feed.xml

episodes:
  - title: "Episode 1"
    description: "This is the *first* episode. You can also include [links](https://foobar.com)."
    publication_date: "2023-02-01T10:00:00"
    asset_url: "https://assets.allsamplefiles.com/mp4/ns/60s/sample-file-quad-hd.mp4"
    episode: 1
    season: 1
    episode_type: "trailer"
    itunes_image: http://example.com/images/episode1.jpg
    link: http://example.com/episode1
  - title: "Episode 2"
    description: "This is the second episode."
    publication_date: "2023-02-08T11:00:00"
    asset_url: "https://assets.allsamplefiles.com/mp4/ns/60s/sample-file-hd.mp4"
    episode: 2
    season: 1
    episode_type: "full"
